# Generated by Django 2.0.6 on 2018-08-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('describe', models.TextField(default='', verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Project')),
            ],
        ),
    ]
