# Generated by Django 2.0.4 on 2018-08-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='Project',
            new_name='project',
        ),
    ]
