# Generated by Django 2.2.2 on 2019-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, verbose_name='session_id')),
                ('device', models.TextField(default='', verbose_name='设备')),
                ('app', models.CharField(max_length=30, verbose_name='App')),
                ('app_version', models.CharField(max_length=10, verbose_name='App版本')),
                ('pushed_time', models.DateTimeField(verbose_name='push_time')),
                ('cpu_usage_avg', models.FloatField(null=True, verbose_name='CPU平均值')),
                ('cpu_usage_median', models.FloatField(null=True, verbose_name='CPU中间值')),
                ('cpu_usage_min', models.FloatField(null=True, verbose_name='CPU最小值')),
                ('cpu_usage_max', models.FloatField(null=True, verbose_name='CPU最大值')),
                ('mem_usage_avg', models.IntegerField(null=True, verbose_name='Memory平均使用率')),
                ('mem_usage_median', models.IntegerField(null=True, verbose_name='Memory中间值')),
                ('mem_usage_min', models.IntegerField(null=True, verbose_name='Memory最小值')),
                ('mem_usage_max', models.IntegerField(null=True, verbose_name='Memory最大值')),
                ('fps_min', models.IntegerField(null=True, verbose_name='FPS最小值')),
                ('fps_max', models.IntegerField(null=True, verbose_name='FPS最大值')),
                ('fps_median', models.IntegerField(null=True, verbose_name='FPS中间价值')),
                ('fps_stability', models.FloatField(null=True, verbose_name='FPS稳定性')),
                ('status', models.BooleanField(default=True, verbose_name='开关')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
