# Generated by Django 2.2.2 on 2019-09-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='platform',
            field=models.CharField(max_length=100, null=True, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='version',
            field=models.CharField(max_length=100, null=True, verbose_name='版本'),
        ),
    ]
