# Generated by Django 2.2.2 on 2019-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_report', '0002_auto_20190902_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='data_time',
            field=models.CharField(max_length=200, null=True, verbose_name='报告日期时间'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='报告完整名称'),
        ),
    ]
