# Generated by Django 2.2.2 on 2019-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_report', '0003_auto_20190902_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='report',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='testsnapshot',
            old_name='report',
            new_name='case',
        ),
        migrations.AddField(
            model_name='testcase',
            name='case_desc',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='用例描述'),
        ),
    ]
