# Generated by Django 2.1.1 on 2018-10-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='mothod',
            new_name='method',
        ),
    ]
