# Generated by Django 2.1.1 on 2018-10-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20181007_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='belong_module',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='belong_project',
            new_name='project',
        ),
    ]
