# Generated by Django 2.0.6 on 2018-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20181007_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='parameter_body',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='参数体'),
        ),
    ]
