# Generated by Django 2.0.6 on 2018-10-22 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface_app', '0004_auto_20181008_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='user',
        ),
        migrations.AddField(
            model_name='testcase',
            name='create_user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
