# Generated by Django 2.1.1 on 2018-11-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0006_testtask'),
        ('interface_app', '0006_remove_testcase_project'),
    ]

    operations = [
    ]
